# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - master


jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: setnode
      uses: actions/setup-node@v1
      with:
       node-version: '12'

    - name: run
      run: |
           npm install
           npm run build

    - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: dist/release.js application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}






